"""add member_id to users

Revision ID: 836c9116ef09
Revises:
Create Date: 2026-05-10 14:19:39.477535

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "836c9116ef09"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("member_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_users_member_id", ["member_id"])
        batch_op.create_foreign_key(
            "fk_users_member_id", "members", ["member_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_member_id", type_="foreignkey")
        batch_op.drop_constraint("uq_users_member_id", type_="unique")
        batch_op.drop_column("member_id")

    # ### end Alembic commands ###
